# Generated by Django 3.0.4 on 2020-03-25 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 0, 8, 16, 184945)),
        ),
    ]
