# Generated by Django 3.0.4 on 2020-03-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
