# Generated by Django 3.0.4 on 2020-03-25 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200326_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 1, 7, 8, 185630)),
        ),
    ]
