# Generated by Django 3.0.4 on 2020-03-25 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200326_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
