# Generated by Django 3.0.4 on 2020-03-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200326_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_time']},
        ),
    ]
