# Generated by Django 3.0.4 on 2020-04-15 16:38

from django.db import migrations, models
import django.utils.timezone
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200326_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=mainApp.models.get_upload_path),
        ),
    ]
