# Generated by Django 3.2.8 on 2021-12-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20210326_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
