# Generated by Django 3.0.4 on 2020-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200311_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
